# Generated by Django 2.2.1 on 2019-07-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
