# Generated by Django 2.2.1 on 2019-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20190725_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('title', 'dashboard')},
        ),
    ]
